ajustes

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -36,7 +36,18 @@ jobs:
         with:
           java-version: 11.0.2
       - name: Build with Maven
-        run: mvn -B package -Pnative --file pom.xml  
+        run: mvn -B package -Pnative --file pom.xml
+
+      - name: Run Tests
+        run: mvn verify
+
+      - name: Test Report
+          uses: dorny/test-reporter@v1
+          if: success() || failure()    # run this step even if previous step failed
+          with:
+            name: JEST Tests            # Name of the check run which will be created
+            path: reports/jest-*.xml    # Path to test results
+            reporter: jest-junit        # Format of test results
 
       - name: Build, Tag, and Push the Image to Amazon ECR
         id: build-image
